site_savalize_homepage:
    pattern:  /
    defaults: { _controller: SiteSavalizeBundle:Default:index }

site_user_page4:
    pattern: /usrhistory
    defaults: { _controller: SiteSavalizeBundle:UserAccount:usrhistory }
    
site_company_page10:
    pattern: /page10
    defaults: { _controller: SiteSavalizeBundle:Company:page10 }
SiteSavalizeBundle_reviews:
    pattern:  /reviews/show
    defaults: { _controller: SiteSavalizeBundle:Default:showReviews }
