SiteSavalizeBundle_brand:
    resource: "@SiteSavalizeBundle/Resources/config/routing/brand.php"
    prefix:   /brand

SiteSavalizeBundle_category:
    resource: "@SiteSavalizeBundle/Resources/config/routing/category.php"
    prefix:   /category

SiteSavalizeBundle_subcategory:
    resource: "@SiteSavalizeBundle/Resources/config/routing/subcategory.php"
    prefix:   /subcategory

SiteSavalizeBundle_company:
    resource: "@SiteSavalizeBundle/Resources/config/routing/company.php"
    prefix:   /company

SiteSavalizeBundle_product:
    resource: "@SiteSavalizeBundle/Resources/config/routing/product.php"
    prefix:   /product

SiteSavalizeBundle_useraccount:
    resource: "@SiteSavalizeBundle/Resources/config/routing/useraccount.php"
    prefix:   /useraccount

SiteSavalizeBundle_adminaccount:
    resource: "@SiteSavalizeBundle/Resources/config/routing/adminaccount.php"
    prefix:   /adminaccount
    
site_savalize_homepage:
    pattern:  /
    defaults: { _controller: SiteSavalizeBundle:Default:index }

#site_ajax_get_date:
#    pattern: /usrhistory/{date}
#    defaults: { controller: SiteSavalizeBundle:UserAccount:historyDateSelection }
#    requirements:
#      date: \d+

site_user_page4:
    pattern: /usrhistory
    defaults: { _controller: SiteSavalizeBundle:UserAccount:historyDateSelection }
    
site_company_page10:
    pattern: /page10
    defaults: { _controller: SiteSavalizeBundle:Company:page10 }

site_savalize_viewNotifications:
    pattern: /show/{id}/{page}
    defaults: { _controller: SiteSavalizeBundle:UserAccount:shownotification }
    requirements:
        page: \d+
        
site_savalize_displayDummyChart:
    pattern: /displayChart
    defaults: { _controller: SiteSavalizeBundle:UserAccount:displayEnteryChartPage }
    
site_savalize_ajaxtoshowchart:
  pattern:  /usr/renderreport
  defaults: { _controller: SiteSavalizeBundle:UserAccount:displayDummyChart }