site_savalize_homepage:
    pattern:  /
    defaults: { _controller: SiteSavalizeBundle:Default:index }

site_user_page4:
    pattern: /usrhistory
    defaults: { _controller: SiteSavalizeBundle:UserAccount:usrhistory }
    
site_company_page10:
    pattern: /page10
    defaults: { _controller: SiteSavalizeBundle:Company:page10 }

SiteSavalizeBundle_reviews:
    pattern:  /reviews/show
    defaults: { _controller: SiteSavalizeBundle:Default:showReviews }
    
contact_us:
  pattern:  /user/contact
  defaults: { _controller: SiteSavalizeBundle:UserAccount:contact }
  
contact_us_company:
  pattern:  /company/contact
  defaults: { _controller: SiteSavalizeBundle:Company:contact }

site_personal_user_settings:
    pattern: /personalusersettings
    defaults: { _controller: SiteSavalizeBundle:UserAccount:personalusersettings }
    
site_category_user_settings:
    pattern: /categoryusersettings
    defaults: { _controller: SiteSavalizeBundle:UserAccount:categoryusersettings }