<?php

namespace Site\SavalizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccountRepository extends EntityRepository
{
//    public function dateRangeData($startDate, $endDate) {
//        $startDate = new \DateTime($startDate);
//        $startDate = $startDate->format("Y-m-d");
//        $endDate = new \DateTime($endDate);
//        $endDate = $endDate->format("Y-m-d");
//        // g stands for graph
//        $q = $this->createQueryBuilder('g');
//        $q->select('g')
//                ->where('g.date >= :startDate')
//                ->andWhere('g.date <= :endDate')
//                ->setParameter('startDate', $startDate)
//                ->setParameter('endDate', $endDate);
//        $result = $q->getQuery()->getResult();
//        return $result;
//    }
}
