<?php

namespace Site\SavalizeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProductController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Site\SavalizeBundle\Controller\ProductController();
        return $instance;
    }
}
